# Twilio Configuration
TWILIO_SID = "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
TWILIO_AUTH = "your_twilio_auth_token"
TWILIO_FROM = "whatsapp:+14155238886"  # Twilio Sandbox or verified number

# Admin Credentials
ADMIN_USER = "admin"

# Create hash in Python:
# import bcrypt; bcrypt.hashpw("yourpassword".encode(), bcrypt.gensalt()).decode()
ADMIN_PASSWORD_HASH = "$2b$12$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
