TWILIO_SID = "your_twilio_account_sid"
TWILIO_AUTH = "your_twilio_auth_token"
TWILIO_FROM = "whatsapp:+14155238886"
ADMIN_USER = "admin"
ADMIN_PASSWORD_HASH = "$2b$12$yZ5wR1lA6...."  # bcrypt hash of your chosen password
